title: jquery.datagrid
version: 0.0.1
svnrev: true
dest: standalone/ui-datagrid/dist/
modules:
  - file: src/ui.datagrid.js
    name: "datagrid"
    destfile: ui.datagrid.js
    depends:
      - src: src/jquery.utils.js
      - src: src/jquery.strings.js
      - src: src/ui.datagrid.colhider.js
      - src: src/ui.datagrid.ledger.js
      - src: src/ui.datagrid.resizable.js
      - src: src/ui.datagrid.selectable.js
      - src: src/ui.datagrid.sortable.js

copy: 
  - src: demo/themes/default/images/*.png
    dest: standalone/ui-datagrid/dist/themes/default/images/
  - src: demo/themes/default/*.css
    dest: standalone/ui-datagrid/dist/themes/default/
  - src: src/img/datagrid/*
    dest: standalone/ui-datagrid/dist/themes/default/images/
  - src: src/jquery.ui.all.js
    dest: standalone/ui-datagrid/page/jquery.ui.all.js
  - src: src/ui.datagrid*.js
    dest: standalone/ui-datagrid/src/

merge:
  - dest: standalone/ui-datagrid/dist/themes/default/ui.datagrid.css
    files:
      - src: src/css/ui.datagrid.css
zip:
  - dest: standalone/ui-datagrid/downloads/ui.datagrid-%v-standalone.zip
    src: standalone/ui-datagrid/
    exclude: [".svn", "downloads", "build.yml", "demo"]

gzip:
  - dest: standalone/ui-datagrid/downloads/ui.datagrid-%v-standalone.tar.gz
    src: standalone/ui-datagrid/
    exclude: [".svn", "downloads", "build.yml", "demo"]

